import { createClient } from '@/utils/supabase/server'
import SmartInput from '@/components/dashboard/smart-input'
import NotesFeed from '@/components/dashboard/notes-feed'
import Link from 'next/link'

// --- Types ---
interface LinkMetadata {
  url: string;
  title: string | null;
  description: string | null;
  image: string | null;
}

interface Note {
  id: number;
  content: string;
  category: 'temporary' | 'fact';
  created_at: string;
  tags: string[] | null;
  link_meta: LinkMetadata | null;
  file_path: string | null;
  file_type: string | null;
  expires_at: string | null;
}

export default async function DashboardPage() {
  const supabase = await createClient()

  // 1. Fetch recent notes (SSR)
  // We fetch the initial state so the page loads instantly with data.
  // The Client Component (NotesFeed) will then take over for updates.
  const { data: rawNotes } = await supabase
    .from('notes')
    .select('*')
    .order('created_at', { ascending: false })
    .limit(20)

  // Ensure type compatibility
  const notes = (rawNotes as any[]) as Note[] | null

  return (
    <main className="w-full max-w-5xl mx-auto space-y-8 pb-20 px-4 md:px-0">
      
      {/* 1. Header Area */}
      <div className="pt-6">
        <h1 className="text-3xl font-bold text-gray-900 tracking-tight">Second Brain</h1>
        <p className="text-gray-500 mt-1">Capture, Organize, and Remember everything.</p>
      </div>

      {/* 2. SMART INPUT (The Gatekeeper) */}
      <section>
        <SmartInput />
      </section>

      {/* 3. NAVIGATION HUB (3 Colored Boxes) */}
      <section className="grid grid-cols-1 md:grid-cols-3 gap-4">
        
        {/* Box 1: Temporary Store */}
        <Link href="/dashboard/Temporary-Store" className="group p-6 rounded-xl bg-orange-50 border border-orange-100 hover:border-orange-300 hover:shadow-md transition-all flex flex-col items-start gap-3">
          <div className="p-3 bg-white rounded-lg shadow-sm text-2xl group-hover:scale-110 transition-transform">
            ⏳
          </div>
          <div>
            <h3 className="font-bold text-orange-900">Temporary Store</h3>
            <p className="text-xs text-orange-700 mt-1">Tasks & reminders. Auto-deletes in 30 days.</p>
          </div>
        </Link>

        {/* Box 2: Brainstorm (Knowledge Aggregator) */}
        <Link href="/dashboard/Brainstorm" className="group p-6 rounded-xl bg-purple-50 border border-purple-100 hover:border-purple-300 hover:shadow-md transition-all flex flex-col items-start gap-3">
          <div className="p-3 bg-white rounded-lg shadow-sm text-2xl group-hover:scale-110 transition-transform">
            🧠
          </div>
          <div>
            <h3 className="font-bold text-purple-900">Brainstorm</h3>
            <p className="text-xs text-purple-700 mt-1">Synthesize facts and discover connections.</p>
          </div>
        </Link>

        {/* Box 3: Flashcards */}
        <Link href="/dashboard/Flashcards" className="group p-6 rounded-xl bg-green-50 border border-green-100 hover:border-green-300 hover:shadow-md transition-all flex flex-col items-start gap-3">
          <div className="p-3 bg-white rounded-lg shadow-sm text-2xl group-hover:scale-110 transition-transform">
            🗂️
          </div>
          <div>
            <h3 className="font-bold text-green-900">Flashcards</h3>
            <p className="text-xs text-green-700 mt-1">Review active recall decks generated by AI.</p>
          </div>
        </Link>

      </section>

      {/* 4. REALTIME NOTES FEED */}
      <section className="space-y-4">
        <h2 className="text-xl font-bold text-gray-800 flex items-center gap-2">
          <span>Recent Captures</span>
          <span className="text-xs font-normal text-gray-400 bg-gray-100 px-2 py-1 rounded-full">{notes?.length || 0}</span>
        </h2>
        
        {/* We pass the server-fetched notes to the client component.
            The client component will listen for 'UPDATE' events (AI tagging) 
            and re-render automatically. */}
        <NotesFeed initialNotes={notes || []} />
      </section>
    </main>
  )
}